version: '3'
services:
  postgres:
    image: 'postgres'
    container_name: 'objection_postgres'
    command: postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off -c random_page_cost=1.0
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  mysql:
    image: 'mysql:5'
    container_name: 'objection_mysql'
    ports:
      - '3306:3306'
    environment:
      - 'MYSQL_ALLOW_EMPTY_PASSWORD=yes'
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: 'objection_mssql'
    ports:
      - '1433:1433'
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password
